In [162]:
# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# Load dataset
cust_lead = pd.read_csv('../../data/CustomerData_LeadGenerator.csv')

# Inspect data
cust_lead.head(10)

,fakeID,b_specialisation_i,b_specialisation_h,b_specialisation_g,b_specialisation_f,b_specialisation_e,b_specialisation_d,b_specialisation_c,b_specialisation_b,b_specialisation_a,...,q_5th Quint by Total HH,q_2017 Purchasing Power: Per Capita,q_2017 Total Population,"q_2017 Pop 15+/Edu: University, Fachhochschule",q_Uni by Total Pop,q_2017 Personal Care: Per Capita,q_2017 Medical Products: Per Capita,q_2017 Personal Effects: Per Capita,b_in_kontakt_gewesen,b_gekauft_gesamt
0,1069_7334,0,0,0,0,0,0,0,0,0,...,0.186735,23730.35,2194057,324656,0.147971,593.19,326.28,235.75,1,1
1,328_2350,0,0,0,1,1,1,0,0,0,...,0.179848,23343.26,1966798,281130,0.142938,588.54,320.36,230.66,1,1
2,865_6285,0,0,0,1,0,1,0,0,0,...,0.184935,23674.18,2149624,320326,0.149015,592.88,325.57,234.82,1,1
3,47_307,0,1,1,0,0,0,0,0,0,...,0.184523,23572.26,2161445,310981,0.143876,590.84,324.06,233.81,1,0
4,342_2513,0,0,0,0,0,1,0,0,0,...,0.189871,23821.63,2302959,334940,0.145439,593.56,327.75,237.41,1,1
5,584_4117,0,1,1,0,1,0,0,0,0,...,0.186277,23729.24,2167697,324246,0.149581,593.43,327.08,235.73,1,1
6,995_7075,0,0,0,0,0,0,0,0,0,...,0.187219,23699.61,2234581,324379,0.145163,592.21,325.95,235.63,1,1
7,143_7711,0,0,0,0,0,0,0,0,0,...,0.248845,24058.93,307435,21676,0.070506,580.52,324.49,248.99,1,1
8,1055_7298,1,0,1,0,0,0,0,0,1,...,0.187963,23773.74,2225683,328527,0.147607,593.51,326.95,236.46,1,1
9,151_4934,0,1,1,0,0,0,0,1,1,...,0.161965,22865.72,247705,25735,0.103894,581.96,346.16,234.65,1,1

In [163]:
# Print summary statistics

cust_lead.describe()

,b_specialisation_i,b_specialisation_h,b_specialisation_g,b_specialisation_f,b_specialisation_e,b_specialisation_d,b_specialisation_c,b_specialisation_b,b_specialisation_a,b_specialisation_j,...,q_5th Quint by Total HH,q_2017 Purchasing Power: Per Capita,q_2017 Total Population,"q_2017 Pop 15+/Edu: University, Fachhochschule",q_Uni by Total Pop,q_2017 Personal Care: Per Capita,q_2017 Medical Products: Per Capita,q_2017 Personal Effects: Per Capita,b_in_kontakt_gewesen,b_gekauft_gesamt
count,3773.000000,3773.000000,3773.000000,3773.000000,3773.000000,3773.000000,3773.000000,3773.000000,3773.000000,3773.000000,...,3773.000000,3773.000000,3.773000e+03,3773.000000,3773.000000,3773.000000,3773.000000,3773.000000,3773.000000,3773.000000
mean,0.218129,0.224225,0.254704,0.111582,0.285449,0.005566,0.002650,0.020408,0.138616,0.254174,...,0.197419,23170.651983,8.257315e+05,111252.936920,0.101737,574.247339,326.438110,234.848630,0.025179,0.015107
std,0.413030,0.417126,0.435753,0.314894,0.451688,0.074407,0.051421,0.141411,0.345592,0.435454,...,0.024973,1147.978703,8.565966e+05,131837.721022,0.039749,22.966321,11.135183,11.018168,0.156689,0.121996
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.100814,19171.140000,3.807000e+03,172.000000,0.027974,490.390000,270.110000,196.450000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.184566,22662.050000,1.780610e+05,11431.000000,0.063095,560.130000,322.380000,231.310000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.195882,23627.240000,3.417850e+05,39282.000000,0.101592,584.000000,325.860000,235.290000,0.000000,0.000000
75%,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.213667,23839.540000,2.023342e+06,298968.000000,0.145630,592.520000,331.930000,238.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,0.269397,26008.530000,2.350279e+06,337338.000000,0.170786,610.140000,363.230000,274.140000,1.000000,1.000000

In [164]:
# Print DataFrame information

cust_lead.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3773 entries, 0 to 3772
Data columns (total 26 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   fakeID                                          3773 non-null   object
 1   b_specialisation_i                              3773 non-null   int64
 2   b_specialisation_h                              3773 non-null   int64
 3   b_specialisation_g                              3773 non-null   int64
 4   b_specialisation_f                              3773 non-null   int64
 5   b_specialisation_e                              3773 non-null   int64
 6   b_specialisation_d                              3773 non-null   int64
 7   b_specialisation_c                              3773 non-null   int64
 8   b_specialisation_b                              3773 non-null   int64
 9   b_specialisation_a                              3773 non-null   int64
 10  b_specialisation_j                              3773 non-null   int64
 11  q_OpeningDays                                   3773 non-null   int64
 12  q_OpeningHours                                  3773 non-null   object
 13  q_2017 Average Household Size                   3773 non-null   float64
 14  q_2017 Total Households                         3773 non-null   int64
 15  q_2017 HHs: 5th Quintile (68.759 and above)     3773 non-null   int64
 16  q_5th Quint by Total HH                         3773 non-null   float64
 17  q_2017 Purchasing Power: Per Capita             3773 non-null   float64
 18  q_2017 Total Population                         3773 non-null   int64
 19  q_2017 Pop 15+/Edu: University, Fachhochschule  3773 non-null   int64
 20  q_Uni by Total Pop                              3773 non-null   float64
 21  q_2017 Personal Care: Per Capita                3773 non-null   float64
 22  q_2017 Medical Products: Per Capita             3773 non-null   float64
 23  q_2017 Personal Effects: Per Capita             3773 non-null   float64
 24  b_in_kontakt_gewesen                            3773 non-null   int64
 25  b_gekauft_gesamt                                3773 non-null   int64
dtypes: float64(7), int64(17), object(2)
memory usage: 766.5+ KB

In [165]:
# Inspect missing values in the dataset

cust_lead.isnull().values.any()
cust_lead.isnull().sum()

fakeID                                            0
b_specialisation_i                                0
b_specialisation_h                                0
b_specialisation_g                                0
b_specialisation_f                                0
b_specialisation_e                                0
b_specialisation_d                                0
b_specialisation_c                                0
b_specialisation_b                                0
b_specialisation_a                                0
b_specialisation_j                                0
q_OpeningDays                                     0
q_OpeningHours                                    0
q_2017 Average Household Size                     0
q_2017 Total Households                           0
q_2017 HHs: 5th Quintile (68.759 and above)       0
q_5th Quint by Total HH                           0
q_2017 Purchasing Power: Per Capita               0
q_2017 Total Population                           0
q_2017 Pop 15+/Edu: University, Fachhochschule    0
q_Uni by Total Pop                                0
q_2017 Personal Care: Per Capita                  0
q_2017 Medical Products: Per Capita               0
q_2017 Personal Effects: Per Capita               0
b_in_kontakt_gewesen                              0
b_gekauft_gesamt                                  0
dtype: int64

#### No missing values found

In [166]:
# Checking duplicates

sum(cust_lead.duplicated(subset = 'fakeID')) == 0

True

#### There are no duplicate rows

In [167]:
# Analysing columns with Object datatype and cleaning data

## Removed the row with invalid values and assigned the column a valid data type 
cust_lead = cust_lead[cust_lead.q_OpeningHours != 'ject']
cust_lead["q_OpeningHours"] = cust_lead.q_OpeningHours.astype(float)

In [168]:
# Opening Days

print("Opening Days: " + str(sorted(cust_lead['q_OpeningDays'].unique())))

Opening Days: [0, 1, 2, 3, 4, 5, 6, 7]

In [173]:
# Because it has fixed values, creating a categorical variable from the field
new_col = cust_lead["q_OpeningDays"].astype("category")
cust_lead.insert(loc=12, column='q_OpeningDays_cat', value=new_col)
cust_lead.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3772 entries, 0 to 3772
Data columns (total 27 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   fakeID                                          3772 non-null   object
 1   b_specialisation_i                              3772 non-null   int64
 2   b_specialisation_h                              3772 non-null   int64
 3   b_specialisation_g                              3772 non-null   int64
 4   b_specialisation_f                              3772 non-null   int64
 5   b_specialisation_e                              3772 non-null   int64
 6   b_specialisation_d                              3772 non-null   int64
 7   b_specialisation_c                              3772 non-null   int64
 8   b_specialisation_b                              3772 non-null   int64
 9   b_specialisation_a                              3772 non-null   int64
 10  b_specialisation_j                              3772 non-null   int64
 11  q_OpeningDays                                   3772 non-null   int64
 12  q_OpeningDays_cat                               3772 non-null   category
 13  q_OpeningHours                                  3772 non-null   float64
 14  q_2017 Average Household Size                   3772 non-null   float64
 15  q_2017 Total Households                         3772 non-null   int64
 16  q_2017 HHs: 5th Quintile (68.759 and above)     3772 non-null   int64
 17  q_5th Quint by Total HH                         3772 non-null   float64
 18  q_2017 Purchasing Power: Per Capita             3772 non-null   float64
 19  q_2017 Total Population                         3772 non-null   int64
 20  q_2017 Pop 15+/Edu: University, Fachhochschule  3772 non-null   int64
 21  q_Uni by Total Pop                              3772 non-null   float64
 22  q_2017 Personal Care: Per Capita                3772 non-null   float64
 23  q_2017 Medical Products: Per Capita             3772 non-null   float64
 24  q_2017 Personal Effects: Per Capita             3772 non-null   float64
 25  b_in_kontakt_gewesen                            3772 non-null   int64
 26  b_gekauft_gesamt                                3772 non-null   int64
dtypes: category(1), float64(8), int64(17), object(1)
memory usage: 928.7+ KB

In [169]:
# Analysing dependent variables

kontakt_gewesen = (sum(cust_lead['b_in_kontakt_gewesen'])/len(cust_lead['b_in_kontakt_gewesen'].index))*100
kontakt_gewesen

2.518557794273595

#### 2.5% of them have made contact

In [202]:
# b_gekauft_gesamt is the actual target variable since we are more interested on ones that got purchased.

gekauft_gesamt = (sum(cust_lead['b_gekauft_gesamt'])/len(cust_lead['b_gekauft_gesamt'].index))*100
gekauft_gesamt

%store cust_lead

Stored 'cust_lead' (DataFrame)

#### 1.5% of them are purchased. This indicates the presence of class imbalance